parameters:
    ezpublish.persistence.legacy.search.gateway.criterion_handler.common.tag_id.class: Netgen\TagsBundle\Core\Persistence\Legacy\Content\Search\Common\Gateway\CriterionHandler\TagId

services:
    ezpublish.persistence.legacy.search.gateway.criterion_handler.common.tag_id:
        parent: ezpublish.persistence.legacy.search.gateway.criterion_handler.base
        class: %ezpublish.persistence.legacy.search.gateway.criterion_handler.common.tag_id.class%
        tags:
            - {name: ezpublish.persistence.legacy.search.gateway.criterion_handler.common}
