parameters:
    ezpublish.fieldType.eztags.converter.class: EzSystems\TagsBundle\Core\Persistence\Legacy\Content\FieldValue\Converter\Tags
    ezpublish.fieldType.eztags.storage_gateway.class: EzSystems\TagsBundle\Core\FieldType\Tags\TagsStorage\Gateway\LegacyStorage

services:
    ezpublish.fieldType.eztags.converter:
        class: %ezpublish.fieldType.eztags.converter.class%
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: eztags, lazy: true, callback: '::create'}

    ezpublish.fieldType.eztags.storage_gateway:
        class: %ezpublish.fieldType.eztags.storage_gateway.class%
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler.gateway, alias: eztags, identifier: LegacyStorage}
