language: php

# run tests on php misc php versions
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

# test only master (+ Pull requests)
branches:
  only:
    - master

# install dependencies
install: composer install --no-dev --prefer-source

# setup requirements for running unit tests
before_script:
  - cp config.php-DEVELOPMENT vendor/ezsystems/ezpublish-kernel/config.php

# execute phpunit as the script command
script:
  - phpunit -d memory_limit=-1 --colors -c phpunit.xml
  - phpunit -d memory_limit=-1 --colors -c phpunit-integration-legacy.xml

# disable mail notifications
notification:
  email: false

# reduce depth (history) of git checkout
git:
  depth: 30
